FROM php:7.2-apache

RUN docker-php-ext-install json
RUN a2enmod rewrite
RUN curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
ADD . /var/www/html
RUN cd /var/www/html \
    && composer install --prefer-dist --no-dev --no-interaction --optimize-autoloader \
    && rm -rf /usr/local/bin/composer

WORKDIR /var/www/html